package Aphorism;

/**
* Aphorism/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public Aphorism.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (Aphorism.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Aphorism.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Aphorism.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Aphorism.AdminHelper.type ();
  }

}
