package Aphorism;


/**
* Aphorism/AdminHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

abstract public class AdminHelper
{
  private static String  _id = "IDL:Aphorism/Admin:1.0";

  public static void insert (org.omg.CORBA.Any a, Aphorism.Admin that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Aphorism.Admin extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Aphorism.AdminHelper.id (), "Admin");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Aphorism.Admin read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdminStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Aphorism.Admin value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Aphorism.Admin narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Aphorism.Admin)
      return (Aphorism.Admin)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Aphorism._AdminStub stub = new Aphorism._AdminStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Aphorism.Admin unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Aphorism.Admin)
      return (Aphorism.Admin)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Aphorism._AdminStub stub = new Aphorism._AdminStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
