package Aphorism;


/**
* Aphorism/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public interface AdminOperations 
{
  boolean createPlayer (String name, String password);
  boolean changePassword (String name, String password);
  boolean deletePlayer (String name);
  void shutdownServer ();
  String[] getnames ();
} // interface AdminOperations
