package Aphorism;


/**
* Aphorism/IllegalOperation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public final class IllegalOperation extends org.omg.CORBA.UserException
{
  public String reason = null;

  public IllegalOperation ()
  {
    super(IllegalOperationHelper.id());
  } // ctor

  public IllegalOperation (String _reason)
  {
    super(IllegalOperationHelper.id());
    reason = _reason;
  } // ctor


  public IllegalOperation (String $reason, String _reason)
  {
    super(IllegalOperationHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class IllegalOperation
