package Aphorism;

/**
* Aphorism/IllegalOperationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public final class IllegalOperationHolder implements org.omg.CORBA.portable.Streamable
{
  public Aphorism.IllegalOperation value = null;

  public IllegalOperationHolder ()
  {
  }

  public IllegalOperationHolder (Aphorism.IllegalOperation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Aphorism.IllegalOperationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Aphorism.IllegalOperationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Aphorism.IllegalOperationHelper.type ();
  }

}
