package Aphorism;


/**
* Aphorism/MoveHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

abstract public class MoveHelper
{
  private static String  _id = "IDL:Aphorism/Move:1.0";

  public static void insert (org.omg.CORBA.Any a, Aphorism.Move that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Aphorism.Move extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (4, _tcOf_members0 );
          _members0[0] = new org.omg.CORBA.StructMember (
            "selections",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Aphorism.MoveHelper.id (), "Move", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Aphorism.Move read (org.omg.CORBA.portable.InputStream istream)
  {
    Aphorism.Move value = new Aphorism.Move ();
    value.selections = new short[4];
    for (int _o0 = 0;_o0 < (4); ++_o0)
    {
      value.selections[_o0] = istream.read_short ();
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Aphorism.Move value)
  {
    if (value.selections.length != (4))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (4); ++_i0)
    {
      ostream.write_short (value.selections[_i0]);
    }
  }

}
