package Aphorism;


/**
* Aphorism/Move.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public final class Move implements org.omg.CORBA.portable.IDLEntity
{
  public short selections[] = null;

  public Move ()
  {
  } // ctor

  public Move (short[] _selections)
  {
    selections = _selections;
  } // ctor

} // class Move
