package Aphorism;

/**
* Aphorism/MoveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public final class MoveHolder implements org.omg.CORBA.portable.Streamable
{
  public Aphorism.Move value = null;

  public MoveHolder ()
  {
  }

  public MoveHolder (Aphorism.Move initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Aphorism.MoveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Aphorism.MoveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Aphorism.MoveHelper.type ();
  }

}
