package Aphorism;


/**
* Aphorism/PlayerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public abstract class PlayerPOA extends org.omg.PortableServer.Servant
 implements Aphorism.PlayerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("create", new java.lang.Integer (0));
    _methods.put ("gamerecord", new java.lang.Integer (1));
    _methods.put ("loadGame", new java.lang.Integer (2));
    _methods.put ("login", new java.lang.Integer (3));
    _methods.put ("recordMove", new java.lang.Integer (4));
    _methods.put ("check", new java.lang.Integer (5));
    _methods.put ("undo", new java.lang.Integer (6));
    _methods.put ("getPuzzle", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Aphorism/Player/create
       {
         short level = in.read_short ();
         String $result = null;
         $result = this.create (level);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Aphorism/Player/gamerecord
       {
         String $result = null;
         $result = this.gamerecord ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // Aphorism/Player/loadGame
       {
         String $result = null;
         $result = this.loadGame ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Aphorism/Player/login
       {
         String password = in.read_string ();
         boolean $result = false;
         $result = this.login (password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // Aphorism/Player/recordMove
       {
         String move = in.read_string ();
         boolean $result = false;
         $result = this.recordMove (move);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // Aphorism/Player/check
       {
         String answer = in.read_string ();
         boolean $result = false;
         $result = this.check (answer);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // Aphorism/Player/undo
       {
         String $result = null;
         $result = this.undo ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // Aphorism/Player/getPuzzle
       {
         String $result = null;
         $result = this.getPuzzle ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Aphorism/Player:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Player _this() 
  {
    return PlayerHelper.narrow(
    super._this_object());
  }

  public Player _this(org.omg.CORBA.ORB orb) 
  {
    return PlayerHelper.narrow(
    super._this_object(orb));
  }


} // class PlayerPOA
