package Aphorism;


/**
* Aphorism/PlayerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public interface PlayerOperations 
{
  String create (short level);
  String gamerecord ();
  String loadGame ();
  boolean login (String password);
  boolean recordMove (String move);
  boolean check (String answer);
  String undo ();
  String getPuzzle ();
} // interface PlayerOperations
