package Aphorism;

/**
* Aphorism/ResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public final class ResultHolder implements org.omg.CORBA.portable.Streamable
{
  public Aphorism.Result value = null;

  public ResultHolder ()
  {
  }

  public ResultHolder (Aphorism.Result initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Aphorism.ResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Aphorism.ResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Aphorism.ResultHelper.type ();
  }

}
