package Aphorism;


/**
* Aphorism/stringlistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idlsrc/Aphorism.idl
* Thursday, September 19, 2013 6:25:01 PM PDT
*/

public final class stringlistHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public stringlistHolder ()
  {
  }

  public stringlistHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Aphorism.stringlistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Aphorism.stringlistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Aphorism.stringlistHelper.type ();
  }

}
